### ISSUE TITLE
ValueError: Unable to configure handler 'file'

### ISSUE THREAD

**Issue by EdisonDragonSlayer** [rafalf/amazon-search-rank#2]
Hello, Raf

I tried it out today, and find some small issues. I'm not a pro programer, and I can't seem to find way to fix this

- When I run 'run.py', I got traceback below

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/config.py", line 744, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/handlers.py", line 146, in __init__
    if maxBytes > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 314, in <module>
    main()
  File "run.py", line 230, in main
    logger = get_logger()
  File "run.py", line 103, in get_logger
    logging.config.dictConfig(LOGGING_CONFIG)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'
```

- So I tried to add int() 
change the code in line from 228 to 233:

```
conf = get_config()
    input_data = get_csv(conf.get(int('input_file')))
    logger = get_logger()
    next_selector = '.a-last>a'
    sponsored_append_selector = '[data-component-type="sp-sponsored-result"]'
```

- Then I got thie traceback:
```
Traceback (most recent call last):
  File "run.py", line 314, in <module>
    main()
  File "run.py", line 229, in main
    input_data = get_csv(conf.get(int('input_file')))
ValueError: invalid literal for int() with base 10: 'input_file'
```

Now I really don't know what to do, could you kindly help?

Also, I found pyyaml updated load() for security reasons, you need to add Loader=yaml.FullLoader
I have change the code from 109 to 112:
```
def get_config():
    with open('config.yaml', 'r') as yaml_file:
        yaml_config = yaml.load(yaml_file, Loader=yaml.FullLoader)
        return yaml_config
```

**Comment by rafalf** [comment]
try Python 2.7 and Firefox 
I just ran it and worked ok
I'm not going to port it to 3.x (unless I get paid for such) as this is an old project that I coded as a freelancer for a client of mine and at a time he was on 2.7
